window.AUDIO_MANIFEST = {
  "Monday": "monday.mp3",
  "Tuesday": "tuesday.mp3",
  "Wednesday": "wednesday.mp3",
  "Thursday": "thursday.mp3",
  "Friday": "friday.mp3",
  "Saturday": "saturday.mp3",
  "Sunday": "sunday.mp3",
  "weekend": "weekend.mp3",
  "day-off": "day-off.mp3",
  "I always drink coffee in the morning.": "i-always-drink-coffee-in-the-morning.mp3",
  "I usually go to the gym on Monday.": "i-usually-go-to-the-gym-on-monday.mp3",
  "We frequently work late on Fridays.": "we-frequently-work-late-on-fridays.mp3",
  "We often meet the client on Fridays.": "we-often-meet-the-client-on-fridays.mp3",
  "I sometimes go out on Saturday.": "i-sometimes-go-out-on-saturday.mp3",
  "I occasionally travel for business.": "i-occasionally-travel-for-business.mp3",
  "He seldom drinks alcohol.": "he-seldom-drinks-alcohol.mp3",
  "He rarely takes a day off.": "he-rarely-takes-a-day-off.mp3",
  "She never smokes.": "she-never-smokes.mp3",
  "Good morning.": "good-morning.mp3",
  "Good afternoon.": "good-afternoon.mp3",
  "Have a good evening. See you tomorrow.": "have-a-good-evening-see-you-tomorrow.mp3",
  "See you later.": "see-you-later.mp3",
  "Good night.": "good-night.mp3",
  "How's it going?": "hows-it-going.mp3",
  "Long time no see!": "long-time-no-see.mp3",
  "What's up?": "whats-up.mp3",
  "Nice to meet you.": "nice-to-meet-you.mp3",
  "How have you been?": "how-have-you-been.mp3",
  "Really?": "really.mp3",
  "No way!": "no-way.mp3",
  "You're kidding!": "youre-kidding.mp3",
  "That's awesome!": "thats-awesome.mp3",
  "I know, right!": "i-know-right.mp3",
  "Could you help me out?": "could-you-help-me-out.mp3",
  "Do you mind if I sit here?": "do-you-mind-if-i-sit-here.mp3",
  "I'd appreciate that.": "id-appreciate-that.mp3",
  "That would be great.": "that-would-be-great.mp3",
  "Thanks anyway.": "thanks-anyway.mp3",
  "Sorry, I didn't catch that.": "sorry-i-didnt-catch-that.mp3",
  "What do you mean?": "what-do-you-mean.mp3",
  "I'm not sure I follow.": "im-not-sure-i-follow.mp3",
  "Could you say that again?": "could-you-say-that-again.mp3",
  "Oh, got it!": "oh-got-it.mp3",
  "Exactly!": "exactly.mp3",
  "Fair enough.": "fair-enough.mp3",
  "I see your point.": "i-see-your-point.mp3",
  "I'm not sure about that.": "im-not-sure-about-that.mp3",
  "You might be right.": "you-might-be-right.mp3",
  "I'm on my way.": "im-on-my-way.mp3",
  "I just woke up.": "i-just-woke-up.mp3",
  "I'm heading home.": "im-heading-home.mp3",
  "Let's grab some coffee.": "lets-grab-some-coffee.mp3",
  "I'll be right back.": "ill-be-right-back.mp3",
  "What time works for you?": "what-time-works-for-you.mp3",
  "Anytime after 3 p.m. works for me.": "anytime-after-3-pm-works-for-me.mp3",
  "Let's set up a call for Friday morning.": "lets-set-up-a-call-for-friday-morning.mp3",
  "My name is Alexander. I am forty-two years old. I have lived in Moscow for the last fifteen years. I work as a CEO in a construction, interior decoration and development company. In my company there are one thousand eight hundred people. I go to the gym twice a week, and once a week I play hockey. I have a hockey team. When I have some free time, I would like to sleep. Japan is my favourite country.": "my-name-is-alexander-i-am-forty-two-years-old-i-ha-afb89cd4.mp3",
  "Hi. I'm Stanislav Pavlov. I am the commercial director at Athon In. I participate in the work of all departments to one degree or another. I have two sales departments directly under my control, one in Moscow and one in Saint Petersburg. I also manage the procurement department. I have about eighty people under my direct command. I will tell you a little about my hobbies. I love reading books. I'm fascinated by the history of ancient Rome. I also go to the gym in my free time. I practice asceticism. I don't drink alcohol or smoke cigarettes. I have a very negative attitude towards drugs. If I drink alcohol, I become insane. That's why I prefer a sober lifestyle. My current goal is to start speaking English.": "hi-im-stanislav-pavlov-i-am-the-commercial-directo-80089379.mp3",
  "CEO": "ceo.mp3",
  "construction": "construction.mp3",
  "interior decoration": "interior-decoration.mp3",
  "development": "development.mp3",
  "a hockey team": "a-hockey-team.mp3",
  "cuisine": "cuisine.mp3",
  "pets": "pets.mp3",
  "a niece": "a-niece.mp3",
  "a nephew": "a-nephew.mp3",
  "siblings": "siblings.mp3",
  "a degree": "a-degree.mp3",
  "current": "current.mp3",
  "goal": "goal.mp3",
  "to tell": "to-tell.mp3",
  "fascinated by": "fascinated-by.mp3",
  "ancient": "ancient.mp3",
  "to practice": "to-practice.mp3",
  "asceticism": "asceticism.mp3",
  "alcohol": "alcohol.mp3",
  "attitude towards": "attitude-towards.mp3",
  "towards": "towards.mp3",
  "to become": "to-become.mp3",
  "insane": "insane.mp3",
  "that's why": "thats-why.mp3",
  "to prefer": "to-prefer.mp3",
  "sober lifestyle": "sober-lifestyle.mp3",
  "to participate in": "to-participate-in.mp3",
  "a department": "a-department.mp3",
  "procurement": "procurement.mp3",
  "under my command": "under-my-command.mp3",
  "to smoke": "to-smoke.mp3",
  "a cigarette": "a-cigarette.mp3",
  "a hobby / hobbies": "a-hobby-hobbies.mp3",
  "a drug": "a-drug.mp3",
  "to do some business": "to-do-some-business.mp3",
  "to relax a little": "to-relax-a-little.mp3",
  "several times a week": "several-times-a-week.mp3",
  "once a week / twice a week": "once-a-week-twice-a-week.mp3",
  "once every 3 months": "once-every-3-months.mp3",
  "Japan is my favourite country": "japan-is-my-favourite-country.mp3",
  "to walk with my dog": "to-walk-with-my-dog.mp3",
  "to watch football with friends": "to-watch-football-with-friends.mp3",
  "to read the news": "to-read-the-news.mp3",
  "commercial director": "commercial-director.mp3",
  "to one degree or another": "to-one-degree-or-another.mp3",
  "a sales department": "a-sales-department.mp3",
  "directly under my control": "directly-under-my-control.mp3",
  "reading books": "reading-books.mp3",
  "in my free time": "in-my-free-time.mp3",
  "to start speaking English": "to-start-speaking-english.mp3",
  "I'll tell you a little about": "ill-tell-you-a-little-about.mp3",
  "My current goal is to": "my-current-goal-is-to.mp3",
  "in the evenings": "in-the-evenings.mp3",
  "to go out": "to-go-out.mp3",
  "to go to the gym": "to-go-to-the-gym.mp3",
  "to have colleagues at the office": "to-have-colleagues-at-the-office.mp3",
  "In the evenings I usually stay at home, but on Friday I go out with colleagues.": "in-the-evenings-i-usually-stay-at-home-but-on-frid-7c610630.mp3",
  "A few colleagues from Berlin came to Moscow last week for a business dinner.": "a-few-colleagues-from-berlin-came-to-moscow-last-w-193d7330.mp3",
  "I have three colleagues at the office. We sit in the same open space and have coffee together at eleven.": "i-have-three-colleagues-at-the-office-we-sit-in-th-6fe6c070.mp3",
  "My colleague is calm and adequate, even after a very long call with a difficult client.": "my-colleague-is-calm-and-adequate-even-after-a-ver-6f2191e9.mp3",
  "Our gym is near the office. I usually go there after work, around seven p.m.": "our-gym-is-near-the-office-i-usually-go-there-afte-d31ee4fb.mp3",
  "In my free time I read the news, walk with my dog, or watch football with friends.": "in-my-free-time-i-read-the-news-walk-with-my-dog-o-fe6cda93.mp3",
  "our company": "our-company.mp3",
  "as a CEO": "as-a-ceo.mp3",
  "1,800 people": "1800-people.mp3",
  "would": "would.mp3",
  "an inadequate man": "an-inadequate-man.mp3",
  "walking": "walking.mp3",
  "I'd like to travel to Italy this autumn.": "id-like-to-travel-to-italy-this-autumn.mp3",
  "I'd like to learn English faster.": "id-like-to-learn-english-faster.mp3",
  "I'd like to meet a client for lunch.": "id-like-to-meet-a-client-for-lunch.mp3",
  "I'd like to speak without long pauses.": "id-like-to-speak-without-long-pauses.mp3",
  "I'd like to read one book per week.": "id-like-to-read-one-book-per-week.mp3",
  "When I have some free time, I read the news.": "when-i-have-some-free-time-i-read-the-news.mp3",
  "When I have some free time, I walk with my dog.": "when-i-have-some-free-time-i-walk-with-my-dog.mp3",
  "When I have some free time, I go to the gym.": "when-i-have-some-free-time-i-go-to-the-gym.mp3",
  "When I have some free time, I would like to sleep.": "when-i-have-some-free-time-i-would-like-to-sleep.mp3",
  "When I have some free time, I watch football with friends.": "when-i-have-some-free-time-i-watch-football-with-friends.mp3",
  "My current goal is to start speaking English.": "my-current-goal-is-to-start-speaking-english.mp3",
  "My current goal is to close three deals this quarter.": "my-current-goal-is-to-close-three-deals-this-quarter.mp3",
  "My current goal is to hire two more managers.": "my-current-goal-is-to-hire-two-more-managers.mp3",
  "My current goal is to run a half-marathon.": "my-current-goal-is-to-run-a-half-marathon.mp3",
  "My current goal is to read one classic novel per month.": "my-current-goal-is-to-read-one-classic-novel-per-month.mp3",
  "I don't drink alcohol or smoke cigarettes.": "i-dont-drink-alcohol-or-smoke-cigarettes.mp3",
  "I don't work on Saturday or take calls after 8 p.m.": "i-dont-work-on-saturday-or-take-calls-after-8-pm.mp3",
  "I don't eat meat or drink coffee after lunch.": "i-dont-eat-meat-or-drink-coffee-after-lunch.mp3",
  "I don't watch TV or scroll socials in bed.": "i-dont-watch-tv-or-scroll-socials-in-bed.mp3",
  "I don't skip the gym or miss my morning walk.": "i-dont-skip-the-gym-or-miss-my-morning-walk.mp3",
  "If I drink alcohol, I become insane.": "if-i-drink-alcohol-i-become-insane.mp3",
  "If I work late, I miss dinner with my family.": "if-i-work-late-i-miss-dinner-with-my-family.mp3",
  "If I skip the gym, I feel less energetic.": "if-i-skip-the-gym-i-feel-less-energetic.mp3",
  "If I don't check email early, I miss important updates.": "if-i-dont-check-email-early-i-miss-important-updates.mp3",
  "If I wake up at six, I feel productive all day.": "if-i-wake-up-at-six-i-feel-productive-all-day.mp3",
  "I'll tell you a little about my hobbies.": "ill-tell-you-a-little-about-my-hobbies.mp3",
  "I'll tell you a little about my team.": "ill-tell-you-a-little-about-my-team.mp3",
  "I'll tell you a little about my morning routine.": "ill-tell-you-a-little-about-my-morning-routine.mp3",
  "I'll tell you a little about my company.": "ill-tell-you-a-little-about-my-company.mp3",
  "I'll tell you a little about my last business trip.": "ill-tell-you-a-little-about-my-last-business-trip.mp3",
  "I have lived in Moscow for the last fifteen years.": "i-have-lived-in-moscow-for-the-last-fifteen-years.mp3",
  "I have lived in St Petersburg for the last eight years.": "i-have-lived-in-st-petersburg-for-the-last-eight-years.mp3",
  "I have lived in London for the last three years.": "i-have-lived-in-london-for-the-last-three-years.mp3",
  "I have lived in Berlin for the last seven years.": "i-have-lived-in-berlin-for-the-last-seven-years.mp3",
  "I have lived in Rome for the last two years.": "i-have-lived-in-rome-for-the-last-two-years.mp3",
  "Twice a week I go to the gym, and once a week I play hockey.": "twice-a-week-i-go-to-the-gym-and-once-a-week-i-play-hockey.mp3",
  "Twice a week I call my parents, and once a week I visit my niece.": "twice-a-week-i-call-my-parents-and-once-a-week-i-v-5a948157.mp3",
  "Twice a week I walk in the park, and once a week I meet friends.": "twice-a-week-i-walk-in-the-park-and-once-a-week-i-4fd8d3d2.mp3",
  "Twice a week I travel to a client, and once a week I take a day off.": "twice-a-week-i-travel-to-a-client-and-once-a-week-50e3e71a.mp3",
  "Twice a week I do sport, and once a week I finish a book.": "twice-a-week-i-do-sport-and-once-a-week-i-finish-a-book.mp3"
};
