window.AUDIO_MANIFEST = {
  "reception": "reception.mp3",
  "check-in": "check-in.mp3",
  "check-out": "check-out.mp3",
  "key card": "key-card.mp3",
  "single room": "single-room.mp3",
  "double room": "double-room.mp3",
  "twin room": "twin-room.mp3",
  "lobby": "lobby.mp3",
  "breakfast is included": "breakfast-is-included.mp3",
  "receipt": "receipt.mp3",
  "Excuse me, is this seat taken?": "excuse-me-is-this-seat-taken.mp3",
  "Oh no, please sit.": "oh-no-please-sit.mp3",
  "Thanks. Is your flight on time?": "thanks-is-your-flight-on-time.mp3",
  "Yes, so far. Fingers crossed!": "yes-so-far-fingers-crossed.mp3",
  "Same here. I am going to Berlin. And you?": "same-here-i-am-going-to-berlin-and-you.mp3",
  "Barcelona — my first time.": "barcelona-my-first-time.mp3",
  "That sounds great!": "that-sounds-great.mp3",
  "Do you know how long this ride to Oxford usually takes?": "do-you-know-how-long-this-ride-t-18188584.mp3",
  "About one and a half hours.": "about-one-and-a-half-hours.mp3",
  "Perfect — just enough time for a podcast.": "perfect-just-enough-time-for-a-podcast.mp3",
  "Or a nap if you are lucky!": "or-a-nap-if-you-are-lucky.mp3",
  "True. Early trains always make me sleepy.": "true-early-trains-always-make-me-sleepy.mp3",
  "Have you taken this route before?": "have-you-taken-this-route-before.mp3",
  "A few times — it is a beautiful ride.": "a-few-times-it-is-a-beautiful-ride.mp3",
  "Good to hear. I am new to this city.": "good-to-hear-i-am-new-to-this-city.mp3",
  "You will love it! Friendly people and great food.": "you-will-love-it-friendly-people-33fb8b74.mp3",
  "Sounds promising. Thanks for the tip!": "sounds-promising-thanks-for-the-tip.mp3",
  "Quite a queue, right?": "quite-a-queue-right.mp3",
  "Yes — must be check-in rush hour.": "yes-must-be-check-in-rush-hour.mp3",
  "I just got in from the airport. You too?": "i-just-got-in-from-the-airport-you-too.mp3",
  "No, I have been here a few days. It is a great city.": "no-i-have-been-here-a-few-days-i-e0589537.mp3",
  "Nice. Any tips for dinner nearby?": "nice-any-tips-for-dinner-nearby.mp3",
  "Beautiful view, isn't it?": "beautiful-view-isnt-it.mp3",
  "Absolutely. Nothing beats sea breeze.": "absolutely-nothing-beats-sea-breeze.mp3",
  "Do you travel by ferry often?": "do-you-travel-by-ferry-often.mp3",
  "Only when I visit my parents. They live on the island.": "only-when-i-visit-my-parents-the-8a384445.mp3",
  "That is lovely. Must be peaceful.": "that-is-lovely-must-be-peaceful.mp3",
  "Good morning. Boarding pass, please. I'm afraid the 9:30 flight to Berlin has been delayed by two hours.": "good-morning-boarding-pass-pleas-a0d6f309.mp3",
  "You're kidding! Two hours?": "youre-kidding-two-hours.mp3",
  "Yes, I'm sorry. May I offer you access to the business lounge?": "yes-im-sorry-may-i-offer-you-acc-fa5d4a9f.mp3",
  "That would be great. Thank you.": "that-would-be-great-thank-you.mp3",
  "Long time no see! How was your flight?": "long-time-no-see-how-was-your-flight.mp3",
  "How's it going? Not bad — I just woke up an hour ago.": "hows-it-going-not-bad-i-just-wok-4aca3bbe.mp3",
  "Let's grab some coffee. There is a café by gate 12.": "lets-grab-some-coffee-there-is-a-02f6f385.mp3",
  "Exactly what I need.": "exactly-what-i-need.mp3",
  "Excuse me — do you mind if I sit here?": "excuse-me-do-you-mind-if-i-sit-here.mp3",
  "Oh no, please.": "oh-no-please.mp3",
  "Could you help me out? Do you know where gate 8 is?": "could-you-help-me-out-do-you-kno-903e86a1.mp3",
  "Sorry, I didn't catch that — which gate?": "sorry-i-didnt-catch-that-which-gate.mp3",
  "Gate 8, please.": "gate-8-please.mp3",
  "Down the corridor, on the left.": "down-the-corridor-on-the-left.mp3",
  "Oh, got it! Thanks.": "oh-got-it-thanks.mp3",
  "I have landed. I'm on my way to the hotel.": "i-have-landed-im-on-my-way-to-the-hotel.mp3",
  "Perfect. What time works for you for the meeting?": "perfect-what-time-works-for-you-2da877f0.mp3",
  "Anytime after 3 p.m. works for me. How about six?": "anytime-after-3-pm-works-for-me-6d8c35aa.mp3",
  "That would be great. See you at six.": "that-would-be-great-see-you-at-six.mp3"
};
